### PR TITLE
Enhancements: Unity Package Conversion, Async Methods, Code Organization

### PR DESCRIPTION
**Pull request by AbolfazlHo**
Greetings,

I'm excited to present a series of enhancements and improvements I've made to the AudioRecorder package. These changes are designed to enhance the overall structure, readability, and maintainability of the codebase. Below is an overview of the key changes:

    Unity Package Conversion: The package has been transitioned to align with Unity's new package conventions. All scripts are now housed within the AudioRecorder directory in the Asset folder. The addition of a package.json and assembly definition file ensures seamless integration with Unity projects.

    Async Methods and UniTask: I've replaced traditional coroutines with more efficient and expressive async methods utilizing the UniTask package. This optimization not only streamlines code but also enhances responsiveness.

    Enhanced Organization: The package's scripts are now categorized into three main sections: Recorder, Player, and Utility. The Utility section encompasses file read and write functionalities. The Player section manages audio playback. The Recorder section is subdivided into Core, Handler, and View parts. The Core section is a central hub accessible across the package, offering flexibility and convenience.

These changes collectively contribute to a cleaner codebase, improved project organization, and better adherence to Unity's recommended practices.

I invite you to review the enhancements I've introduced and consider merging them into the main repository. Your feedback and insights would be greatly appreciated.

Warm regards,
Abolfazl

### CODE REVIEW

**Comment by AgrMayank** [comment]
Hi Abolfazl,

The enhancements look good and will make the project much better for other people! 

I'll check & approve the changes before merging the PR into the main branch.

Have a great day!

**Comment by AgrMayank** [comment]
Hi, there are couple of issues in the PR,

- UI is broken and is not scaling with screen.
- I'm getting a Null reference in the scene,
- Along with some webRequests which I'm sure aren't needed for a local audio player. 

Please fix these issues and create new PR with the changes.

image

**Comment by AbolfazlHo** [comment]
Dear AgrMayank,

I hope this message finds you well. I noticed that the Unitask package is
not included in the project as it is a dependency for the package. Please
check if there is a "UniTask" folder within the "Packages" folder. If it is
not present, you can add it to your project from the following repository:
https://github.com/Cysharp/UniTask.
After adding the package, please attach the assembly definition of Unitask
to the assembly definition of AudioRecorder. Please note that you only need
to do this when developing the package. When somebody wants to use the
package, all its dependencies will be added automatically.
Thank you for your attention to this matter. Please let me know if you have
any questions or concerns.

Best regards,
Abolfazl

**Comment by AgrMayank** [comment]
> 

Hi, I'm doing great! Hope you're as well!

Regarding the package, I was hoping to have this project without any 3rd party dependencies., a simple plug-and-play.

Even if we keep the package, there are other issues like the scene UI not working and so on that's why I cannot merge this PR at the moment.

Thanks!

**Pull request closed without merging**
